# Generated by Django 5.0 on 2024-01-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('img', models.FileField(blank=True, null=True, upload_to='movies/img')),
            ],
        ),
    ]
